name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 14 11 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Install Vim
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y vim

    - name: Intall Vim
      uses: rhysd/action-setup-vim@v1

    - name: Run tests
      run: |
        ./test/run_tests
