name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 14 11 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_matrix:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Vim
      uses: rhysd/action-setup-vim@v1
    - name: Run tests
      run: |
        ./test/run_tests

  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - test_matrix
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
