name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 14 11 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Vim
      run: |
        sudo apt-get update
        sudo apt-get install -y vim

    - name: Run tests
      run: |
        # DEBUG BEGIN
        echo >&2 "*** CHUCK $(basename "${BASH_SOURCE[0]}") PWD: ${PWD}"
        find . >&2
        which vim
        # DEBUG END
        ./test/run_tests
